In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/datasets/lainguyn123/student-performance-factors/StudentPerformanceFactors.csv')

In [3]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [4]:
import os
os.listdir('/kaggle/input')

['datasets']

In [5]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [6]:
%load_ext sql

In [7]:
import sqlite3

In [8]:
conn = sqlite3.connect('student.db')

In [9]:
%sql sqlite:///student.db

In [10]:
%%sql

CREATE TABLE students (
    student_id INT,
    name TEXT,
    marks INT
);

 * sqlite:///student.db
Done.

[]

In [11]:
%%sql

INSERT INTO students VALUES
(1, 'Khushi', 90),
(2, 'Rahul', 75),
(3, 'Anjali', 88);

 * sqlite:///student.db
3 rows affected.

[]

In [12]:
import sqlite3
import pandas as pd

# Database connect
conn = sqlite3.connect("student.db")

# Cursor create
cursor = conn.cursor()

# Table create
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER,
    name TEXT,
    marks INTEGER
)
""")

# Data insert
cursor.execute("INSERT INTO students VALUES (1,'Khushi',90)")
cursor.execute("INSERT INTO students VALUES (2,'Rahul',75)")
cursor.execute("INSERT INTO students VALUES (3,'Anjali',88)")

conn.commit()

# SQL query run
query = "SELECT * FROM students"

df = pd.read_sql_query(query, conn)

df

   student_id    name  marks
0           1  Khushi     90
1           2   Rahul     75
2           3  Anjali     88
3           1  Khushi     90
4           2   Rahul     75
5           3  Anjali     88

In [13]:
query = "SELECT * FROM students ORDER BY marks DESC LIMIT 1"

df = pd.read_sql_query(query, conn)

df

   student_id    name  marks
0           1  Khushi     90

In [14]:
query = "SELECT AVG(marks) AS Average_Marks FROM students"

df = pd.read_sql_query(query, conn)

df

   Average_Marks
0      84.333333

In [15]:
query = "SELECT MAX(marks) AS Highest_Marks FROM students"

df = pd.read_sql_query(query, conn)

df

   Highest_Marks
0             90

In [16]:
query = "SELECT * FROM students WHERE marks > 80"

df = pd.read_sql_query(query, conn)

df

   student_id    name  marks
0           1  Khushi     90
1           3  Anjali     88
2           1  Khushi     90
3           3  Anjali     88